apiVersion: apps/v1
kind: Deployment
metadata:
  name: task-sorter
spec:
  replicas: 3
  selector:
    matchLabels:
      app: task-sorter
  template:
    metadata:
      labels:
        app: task-sorter
    spec:
      containers:
        - name: task-sorter
          image: task-sorter:latest
          ports:
            - containerPort: 4000
          resources:
            requests:
              cpu: 300m